# Generated by Django 3.0.8 on 2020-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.IntegerField(verbose_name='your-phone')),
                ('email', models.EmailField(max_length=254)),
                ('schedule', models.CharField(max_length=15)),
                ('day', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
