# Generated by Django 3.1.3 on 2020-11-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Service',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
